# Generated by Django 4.2.4 on 2023-09-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%Y/%M/%D/')),
                ('designation', models.CharField(max_length=100)),
                ('instagram_link', models.URLField(max_length=100)),
                ('facebook_link', models.URLField(max_length=100)),
            ],
        ),
    ]
