# Generated by Django 4.2.4 on 2023-09-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_team_delete_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
